[package]
name = "encoding_rs"
description = "A Gecko-oriented implementation of the Encoding Standard"
version = "0.2.2"
authors = ["Henri Sivonen <hsivonen@hsivonen.fi>"]
license = "MIT/Apache-2.0"
readme = "README.md"
documentation = "https://hsivonen.fi/rs/encoding_rs/"
homepage = "https://hsivonen.fi/rs/encoding_rs/"
repository = "https://github.com/hsivonen/encoding_rs"
keywords = ["encoding", "web", "unicode", "charset"]
build = "build.rs"

[lib]
name = "encoding_rs"
# The below line confuses rustfmt. Uncomment to build a staticlib.
# crate-type = ["rlib", "staticlib"]

[build-dependencies]
rusty-cheddar = "0.3.1"

[profile.release]
lto = true
